import { Router } from 'express';
import commentAdd from './comment.add';
import create from './create';
import deleteMark from './delete.mark';
import detail from './detail';
import edit from './edit';
import get from './get';
import like from './like';
import list from './list';
import mark from './mark';
import profile from './profile';
import staffPick from './staff.pick';
import trending from './trending,';

export default (app: Router) => {
    const route = Router();
    app.use("/blog",route);
    create(route);
    get(route);
    commentAdd(route);
    like(route);
    list(route);
    profile(route);
    detail(route);
    trending(route);
    staffPick(route);
    edit(route);
    mark(route);
    deleteMark(route);
};