import { Router } from 'express';
import authentication from './routes/authentication';
import me from './routes/me';
import test from './test';
import upload from './routes/upload';
import blog from './routes/blog';
import emotion from './routes/emotion';
import notifications from './routes/notifications';
import chat from './routes/chat';
import relationship from './routes/relationship';
import search from './routes/search';
import user from './routes/user';
import admin from './routes/admin';

export default () => {
    const app = Router();
    authentication(app);
    me(app);
    test(app);
    blog(app);
    upload(app);
    emotion(app);
    notifications(app);
    chat(app);
    relationship(app);
    search(app);
    user(app);
    admin(app);
    return app;
};